# Dockerfile for launching dch tool
#
# Usage (always use bullseye as it is replaced before build) :
#   docker build -t deb-dch -f Dockerfile-deb-dch .
#   docker run -it -v $PWD:/local -e HOME=/local deb-dch bash -c 'cd /local && \
#       dch -M -v 1.13.35.2+nginx-1.21.0-1~bullseye --distribution "bullseye" "Updated upstream."'
#

ARG DISTRIB=debian
ARG RELEASE=bullseye

FROM debian:bullseye
LABEL org.opencontainers.image.authors="Cyril Aknine <caknine@clever-age.com>"

ENV TZ=Europe/Paris

RUN apt-get update && apt-get --no-install-recommends --no-install-suggests -y install devscripts libdistro-info-perl
